version: '2'
services:
  lab-mongo-express:
    image: mongo-express
    container_name: lab-mongo_express
    ports:
      - 9081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: lab-mongo-db
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: q
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
    links:
      - lab-mongo-db
    networks:
      - lab-mongo-network

  lab-mongo-db:
    image: mongo:latest
    container_name: lab-mongo_server
    environment:
      MONGO_INITDB_DATABASE: admin  
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - lab-mongo-network

volumes:
  mongodb_data_container:

networks: 
    lab-mongo-network:
      driver: bridge